[workspace]
members = ["workspace-hack"]
resolver = "3"

[workspace.dependencies]
workspace-hack = { path = "./workspace-hack" }

[workspace.lints.clippy]
all = "deny"
expect_used = "deny"
nursery = "deny"
panic = "deny"
pedantic = "deny"
todo = "deny"
unimplemented = "deny"
unwrap_used = "deny"

[workspace.lints.rust]
future_incompatible = "deny"
unsafe_code = "deny"
unused = "deny"

[workspace.metadata.crane]
name = "labs"

[workspace.package]
edition = "2024"
version = "0.0.0"
