//! Emits the generated Rust source for the `echonet-lite` runtime crate.

use crate::ir::{
    Access, ClassFile, ClassKind, Data, Model, PropertyEntry, sanitize_ident, to_camel_case,
};
use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;

/// Deterministic dedup of short names within a single class.
///
/// Assigns each property a unique rust-safe snake_case identifier. The first
/// occurrence of a short name keeps it; duplicates get a numeric suffix ordered by
/// EPC (and declaration order within an EPC).
fn per_class_idents(entries: &[PropertyEntry]) -> Vec<(u8, String)> {
    // Group by EPC first (entries are already in declaration order per file).
    let mut by_epc: BTreeMap<u8, Vec<&PropertyEntry>> = BTreeMap::new();
    for e in entries {
        by_epc.entry(e.epc).or_default().push(e);
    }
    let mut used = BTreeSet::new();
    let mut out = Vec::new();
    for (_epc, list) in by_epc {
        for e in list {
            let ident = sanitize_ident(&e.raw_short_name, &mut used);
            out.push((e.epc, ident));
        }
    }
    out
}

fn access_str(a: Access) -> &'static str {
    match a {
        Access::Required => "Required",
        Access::Optional => "Optional",
        Access::NotApplicable => "NotApplicable",
    }
}

fn data_comment(en: &str) -> String {
    if en.is_empty() {
        String::new()
    } else {
        en.replace('\n', " ").replace('\r', "")
    }
}

/// Emit all generated files into `out_dir`.
pub fn emit(
    model: &Model,
    out_dir: &Path,
) -> Result<(), String> {
    let classes_rs = normalize_eof(render_classes(model)?);
    let properties_rs = normalize_eof(render_properties(model)?);

    std::fs::create_dir_all(out_dir).map_err(|e| format!("create {out_dir:?}: {e}"))?;

    write_file(&out_dir.join("classes.rs"), &classes_rs)?;
    write_file(&out_dir.join("properties.rs"), &properties_rs)?;

    Ok(())
}

/// Ensure the emitted file ends with exactly one trailing newline.
fn normalize_eof(mut s: String) -> String {
    while s.ends_with('\n') {
        s.pop();
    }
    s.push('\n');
    s
}

fn write_file(
    path: &Path,
    contents: &str,
) -> Result<(), String> {
    std::fs::write(path, contents).map_err(|e| format!("write {path:?}: {e}"))
}

fn render_classes(model: &Model) -> Result<String, String> {
    let mut o = String::new();
    o.push_str("// @generated by echonet-lite-codegen. Do not edit.\n");
    o.push_str(&format!(
        "// Source: ECHONET Lite Machine Readable Appendix dataVersion {}\n\n",
        model.metadata_version.as_deref().unwrap_or("unknown")
    ));

    // Eoj enum.
    let mut used_eoj = BTreeSet::new();
    let eoj_variants: Vec<(u16, String, &str)> = model
        .classes
        .iter()
        .map(|c| {
            let name = to_camel_case(&eoj_variant_name(c, &mut used_eoj));
            (c.class, name, c.class_name_en.as_str())
        })
        .collect();
    o.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\n");
    o.push_str("pub enum Eoj {\n");
    for (_, name, doc) in &eoj_variants {
        o.push_str(&format!("    /// {doc}\n"));
        o.push_str(&format!("    {name},\n"));
    }
    o.push_str("    /// A class code not present in this appendix version.\n");
    o.push_str("    Unknown(u16),\n");
    o.push_str("}\n\n");

    o.push_str("impl Eoj {\n");
    o.push_str("    /// Two-byte class code (class group + class), e.g. `0x0002`.\n");
    o.push_str("    #[must_use]\n");
    o.push_str("    pub const fn class_code(self) -> u16 {\n");
    o.push_str("        match self {\n");
    for (code, name, _) in &eoj_variants {
        o.push_str(&format!("            Self::{name} => 0x{code:04X},\n"));
    }
    o.push_str("            Self::Unknown(v) => v,\n");
    o.push_str("        }\n");
    o.push_str("    }\n\n");
    o.push_str("    /// Resolve a raw two-byte class code to the known variant, or\n");
    o.push_str("    /// [`Self::Unknown`] when the class is not in this appendix version.\n");
    o.push_str("    #[must_use]\n");
    o.push_str("    pub const fn from_code(code: u16) -> Self {\n");
    o.push_str("        match code {\n");
    for (code, name, _) in &eoj_variants {
        o.push_str(&format!("            0x{code:04X} => Self::{name},\n"));
    }
    o.push_str("            other => Self::Unknown(other),\n");
    o.push_str("        }\n");
    o.push_str("    }\n");
    o.push_str("}\n\n");

    // Per-class Epc enums.
    for c in &model.classes {
        let entries = model
            .properties
            .get(&c.class)
            .map(Vec::as_slice)
            .unwrap_or(&[]);
        let idents = per_class_idents(entries);
        // Deduplicate by EPC (a class may carry the same EPC across releases);
        // keep the first occurrence's identifier for the codec.
        let mut seen_epc = BTreeSet::new();
        let variants: Vec<(u8, String)> = idents
            .iter()
            .filter(|(epc, _)| seen_epc.insert(*epc))
            .map(|(epc, ident)| {
                let mut camel = to_camel_case(ident);
                if camel == "Unknown" {
                    camel.push('_');
                }
                (*epc, camel)
            })
            .collect();

        let module = class_module_name(c.class);
        o.push_str(&format!(
            "/// Properties of class 0x{:04X} ({}) [{}]\n",
            c.class,
            c.class_name_en,
            kind_str(c.kind)
        ));
        o.push_str(&format!("pub mod {module} {{\n"));
        o.push_str("    /// ECHONET Lite property code (EPC).\n");
        o.push_str("    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\n");
        o.push_str("    #[non_exhaustive]\n");
        o.push_str("    pub enum Epc {\n");
        for (epc, camel) in &variants {
            o.push_str(&format!("        /// `0x{epc:02X}`\n"));
            o.push_str(&format!("        {camel},\n"));
        }
        o.push_str("        /// An EPC not in the appendix for this class.\n");
        o.push_str("        Unknown(u8),\n");
        o.push_str("    }\n\n");
        o.push_str("    impl Epc {\n");
        o.push_str("        /// Raw EPC byte.\n");
        o.push_str("        #[must_use]\n");
        o.push_str("        pub const fn code(self) -> u8 {\n");
        o.push_str("            match self {\n");
        for (epc, camel) in &variants {
            o.push_str(&format!("                Self::{camel} => 0x{epc:02X},\n"));
        }
        o.push_str("                Self::Unknown(v) => v,\n");
        o.push_str("            }\n");
        o.push_str("        }\n\n");
        o.push_str("        /// Convert a raw byte to the known variant if present.\n");
        o.push_str("        #[must_use]\n");
        o.push_str("        pub const fn from_code(code: u8) -> Self {\n");
        o.push_str("            match code {\n");
        for (epc, camel) in &variants {
            o.push_str(&format!("                0x{epc:02X} => Self::{camel},\n"));
        }
        o.push_str("                other => Self::Unknown(other),\n");
        o.push_str("            }\n");
        o.push_str("        }\n");
        o.push_str("    }\n");
        o.push_str("}\n\n");
    }

    Ok(o)
}

fn render_properties(model: &Model) -> Result<String, String> {
    let mut o = String::new();
    o.push_str("// @generated by echonet-lite-codegen. Do not edit.\n");
    o.push_str("// Property metadata table.\n\n");

    o.push_str("use crate::ecodec::{Access, DataKind, PropertyInfo, StateVariant};\n\n");

    // Emit a per-class const table of PropertyInfo.
    let mut class_codes: Vec<u16> = model.classes.iter().map(|c| c.class).collect();
    class_codes.sort_unstable();

    for c in &model.classes {
        let entries = model
            .properties
            .get(&c.class)
            .map(Vec::as_slice)
            .unwrap_or(&[]);
        // Only the latest occurrence of each epc's data is used for the codec per
        // policy; emit one info row per epc.
        let idents = per_class_idents(entries);
        let mut epc_data: BTreeMap<u8, &PropertyEntry> = BTreeMap::new();
        for e in entries {
            epc_data.insert(e.epc, e);
        }

        o.push_str(&format!(
            "pub const PROPERTIES_{:04X}: &[PropertyInfo] = &[\n",
            c.class
        ));
        let mut emitted_epcs: BTreeSet<u8> = BTreeSet::new();
        for (epc, _ident) in &idents {
            if !emitted_epcs.insert(*epc) {
                continue;
            }
            let Some(entry) = epc_data.get(epc) else {
                continue;
            };
            o.push_str(&format!(
                "    PropertyInfo {{
        class: 0x{:04X},
        epc: 0x{epc:02X},
        name: {:?},
        get: Access::{},
        set: Access::{},
        inf: Access::{},
        kind: DataKind::{},
        size: {}u8,
        min_size: {}u8,
        max_size: {}u8,
        scale_num: {}u32,
        scale_den: {}u32,
        signed: {},
        min: {}i64,
        max: {}i64,
        unit: {:?},
        level_base: {}u8,
        level_max: {}u8,
        doc: {:?},
    }},\n",
                c.class,
                entry.name_en,
                access_str(entry.get),
                access_str(entry.set),
                access_str(entry.inf),
                data_kind(&entry.data),
                fixed_size(&entry.data).unwrap_or(0),
                min_size(&entry.data),
                max_size(&entry.data),
                scale(&entry.data).0,
                scale(&entry.data).1,
                signed(&entry.data),
                fmt_i64(min_int(&entry.data)),
                fmt_i64(max_int(&entry.data)),
                unit_str(&entry.data),
                level_base(&entry.data),
                level_max(&entry.data),
                data_comment(&entry.description_en),
            ));
        }
        o.push_str("];\n\n");

        // State variant tables for this class.
        for (epc, entry) in &epc_data {
            if let Data::State { variants, .. } = &entry.data {
                o.push_str(&format!(
                    "pub const STATE_{:04X}_{:02X}: &[StateVariant] = &[\n",
                    c.class, epc
                ));
                for (edt, name, _desc) in variants {
                    let bytes = edt
                        .iter()
                        .map(|b| format!("0x{b:02X}"))
                        .collect::<Vec<_>>()
                        .join(", ");
                    o.push_str(&format!(
                        "    StateVariant {{ edt: &[{bytes}], name: {:?} }},\n",
                        name
                    ));
                }
                o.push_str("];\n\n");
            }
        }

        // Valid-value tables for enum-typed numbers.
        for (epc, entry) in &epc_data {
            let vals = valid_values(&entry.data);
            if !vals.is_empty() {
                o.push_str(&format!(
                    "pub const VALID_{:04X}_{:02X}: &[i64] = &[\n",
                    c.class, epc
                ));
                for v in vals {
                    o.push_str(&format!("    {}i64,\n", fmt_i128(*v)));
                }
                o.push_str("];\n\n");
            }
        }
    }

    // Resolver function for property metadata.
    o.push_str("/// Return the property metadata for a class code.\n");
    o.push_str("#[must_use]\n");
    o.push_str("pub fn class_properties(class: u16) -> &'static [PropertyInfo] {\n");
    o.push_str("    match class {\n");
    for c in &class_codes {
        o.push_str(&format!("        0x{c:04X} => PROPERTIES_{c:04X},\n"));
    }
    o.push_str("        _ => &[],\n");
    o.push_str("    }\n");
    o.push_str("}\n\n");

    // Resolver function for state variant tables.
    o.push_str("/// Return the state variant table for a class/EPC (empty if not a state).\n");
    o.push_str("#[must_use]\n");
    o.push_str("pub fn state_variants(class: u16, epc: u8) -> &'static [StateVariant] {\n");
    o.push_str("    match (class, epc) {\n");
    for c in &model.classes {
        let entries = model
            .properties
            .get(&c.class)
            .map(Vec::as_slice)
            .unwrap_or(&[]);
        let mut epc_data: BTreeMap<u8, &PropertyEntry> = BTreeMap::new();
        for e in entries {
            epc_data.insert(e.epc, e);
        }
        for (epc, entry) in &epc_data {
            if let Data::State { .. } = &entry.data {
                o.push_str(&format!(
                    "        (0x{:04X}, 0x{epc:02X}) => STATE_{:04X}_{epc:02X},\n",
                    c.class, c.class
                ));
            }
        }
    }
    o.push_str("        _ => &[],\n");
    o.push_str("    }\n");
    o.push_str("}\n\n");

    // Resolver for enum-typed numbers' allowed values.
    o.push_str(
        "/// True when `raw` is an allowed value for a numeric property, considering\n/// both its range and any explicit value list.\n",
    );
    o.push_str("#[must_use]\n");
    o.push_str("pub fn number_allowed(class: u16, epc: u8, raw: i64) -> bool {\n");
    o.push_str("    match (class, epc) {\n");
    for c in &model.classes {
        let entries = model
            .properties
            .get(&c.class)
            .map(Vec::as_slice)
            .unwrap_or(&[]);
        let mut epc_data: BTreeMap<u8, &PropertyEntry> = BTreeMap::new();
        for e in entries {
            epc_data.insert(e.epc, e);
        }
        for (epc, entry) in &epc_data {
            if !valid_values(&entry.data).is_empty() {
                o.push_str(&format!(
                    "        (0x{:04X}, 0x{epc:02X}) => VALID_{:04X}_{epc:02X}.contains(&raw),\n",
                    c.class, c.class
                ));
            }
        }
    }
    o.push_str("        _ => true,\n");
    o.push_str("    }\n");
    o.push_str("}\n");

    Ok(o)
}

fn eoj_variant_name(
    c: &ClassFile,
    used: &mut BTreeSet<String>,
) -> String {
    sanitize_ident(c.short_name.as_str(), used)
}

fn class_module_name(class: u16) -> String {
    format!("class_{class:04x}")
}

fn kind_str(kind: ClassKind) -> &'static str {
    match kind {
        ClassKind::Device => "device",
        ClassKind::SuperClass => "super class",
        ClassKind::NodeProfile => "node profile",
    }
}

fn data_kind(d: &Data) -> &'static str {
    match d {
        Data::Number { .. } => "Number",
        Data::State { .. } => "State",
        Data::Raw { .. } => "Raw",
        Data::Level { .. } => "Level",
        Data::Time { .. } => "Time",
        Data::Date { .. } => "Date",
        Data::Object { .. } => "Object",
        Data::Array { .. } => "Array",
        Data::OneOf(_) => "Raw",
    }
}

fn fixed_size(d: &Data) -> Option<usize> {
    match d {
        Data::Number { size, .. } => Some(*size),
        Data::State { size, .. } => Some(*size),
        Data::Raw { min_size, max_size } if min_size == max_size => Some(*min_size),
        Data::Level { .. } => Some(1),
        Data::Time { size } => Some(*size),
        Data::Date { size } => Some(*size),
        _ => None,
    }
}

fn min_size(d: &Data) -> usize {
    match d {
        Data::Raw { min_size, .. } => *min_size,
        Data::Array { item_size, .. } => *item_size,
        Data::Object { fields } => fields.iter().map(|f| min_size(&f.data)).sum(),
        Data::OneOf(v) => v.iter().map(min_size).min().unwrap_or(0),
        other => fixed_size(other).unwrap_or(1),
    }
}

fn max_size(d: &Data) -> usize {
    match d {
        Data::Raw { max_size, .. } => *max_size,
        Data::Array {
            item_size,
            max_items,
            ..
        } => item_size * max_items,
        Data::Object { fields } => fields.iter().map(|f| max_size(&f.data)).sum(),
        Data::OneOf(v) => v.iter().map(max_size).max().unwrap_or(1),
        other => fixed_size(other).unwrap_or(1),
    }
}

fn scale(d: &Data) -> (u32, u32) {
    match d {
        Data::Number { scale: Some(s), .. } => *s,
        _ => (1, 1),
    }
}

fn signed(d: &Data) -> bool {
    matches!(d, Data::Number { signed: true, .. })
}

fn min_int(d: &Data) -> i64 {
    match d {
        Data::Number { min, .. } => *min as i64,
        _ => 0,
    }
}

fn max_int(d: &Data) -> i64 {
    match d {
        Data::Number { max, .. } => *max as i64,
        _ => 0,
    }
}

fn unit_str(d: &Data) -> &str {
    match d {
        Data::Number {
            unit: Some(unit), ..
        } => unit,
        _ => "",
    }
}

fn level_base(d: &Data) -> u8 {
    match d {
        Data::Level { base, .. } => *base,
        _ => 0,
    }
}

fn level_max(d: &Data) -> u8 {
    match d {
        Data::Level { maximum, .. } => *maximum,
        _ => 0,
    }
}

/// The explicit valid values for an enum-typed number (empty for range numbers).
fn valid_values(d: &Data) -> &[i128] {
    match d {
        Data::Number { valid_values, .. } => valid_values,
        _ => &[],
    }
}

/// Format an integer with `_` thousands separators so generated literals pass
/// `clippy::unreadable_literal`.
fn fmt_i128(v: i128) -> String {
    let neg = v < 0;
    let s = v.unsigned_abs().to_string();
    let n = s.len();
    let mut out = String::with_capacity(n + n / 3 + 1);
    for (i, c) in s.chars().enumerate() {
        if i > 0 && (n - i).is_multiple_of(3) {
            out.push('_');
        }
        out.push(c);
    }
    if neg {
        out.insert(0, '-');
    }
    out
}

fn fmt_i64(v: i64) -> String {
    fmt_i128(i128::from(v))
}
